apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
        - name: my-web-app
          image: my-web-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: pyhton-web-app-service
spec:
  selector:
    app: my-web-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
